baseURL = "http://thecontentium.netlify.app"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "The Contentium"
[markup.goldmark.renderer]
unsafe = true
